# Generated by Django 4.1.3 on 2022-11-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_horario',
            new_name='data_horario_agendamento',
        ),
    ]
