# Generated by Django 4.1.3 on 2022-11-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_app', '0002_rename_data_horario_agendamento_data_horario_agendamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_horario_agendamento',
            field=models.DateTimeField(),
        ),
    ]
